# Generated by Django 5.1.5 on 2025-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='nationality',
            new_name='country',
        ),
    ]
