# Generated by Django 5.1.5 on 2025-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(blank=True, choices=[('UNITED STATES', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('SPAIN', 'Espanha'), ('FRANCE', 'França'), ('MEXICO', 'México'), ('ARGENTINA', 'Argentina'), ('UNITED KINGDOM', 'Reino Unido'), ('SOUTH AFRICA', 'África do Sul'), ('INDIA', 'Índia'), ('HONG KONG', 'Hong Kong'), ('ISRAEL', 'Israel'), ('AUSTRALIA', 'Austrália'), ('CANADA', 'Canadá'), ('IRELAND', 'Irlanda'), ('KENYA', 'Quênia'), ('EGYPT', 'Egito')], max_length=100, null=True),
        ),
    ]
